# Travis configuration
language: python

# enable docker
services:
 - docker

script:
 - scripts/run_python35.sh
 - scripts/run_perl520.sh
 - scripts/run_ruby23.sh
 - scripts/run_php56.sh
 - scripts/run_gcc5.sh
 - scripts/run_nodejs6.sh
 - scripts/run_java8.sh

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
