# Travis configuration
language: python

# enable docker
services:
 - docker

script:
 - scripts/run_python35.sh
 - scripts/run_pypy5.sh
 - scripts/run_perl520.sh
 - scripts/run_ruby23.sh
 - scripts/run_php56.sh
 - scripts/run_gcc5.sh
 - scripts/run_gcc5_c.sh
 - scripts/run_nodejs6.sh
 - scripts/run_java8.sh
 - scripts/run_freebasic.sh
 - scripts/run_freepascal.sh
 - scripts/run_d.sh
 - scripts/run_mono.sh
 - scripts/run_scala.sh
 - scripts/run_groovy.sh
 - scripts/run_go.sh
 - scripts/run_kotlin.sh
 - scripts/run_lua.sh
 - scripts/run_dart.sh

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
