# Travis configuration
language: python

# enable docker
services:
 - docker

script:
 - scripts/run_python35.sh
 - scripts/run_perl520.sh

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
